version: "3"
services:
  dev:
    build: .
    volumes:
      - .:/app
    ports:
      - 3000:3000
  
  prod:
    image: nginx
    volumes:
      - ./build:/usr/share/nginx/html
    ports:
      - 80:80
